laravel-breeze/routes/web.php
<?php

use App\Http\Controllers\Admin\BackOfficeController;
use App\Http\Controllers\ContactFormController;
use App\Http\Controllers\ShoppingListController;
use App\Http\Controllers\Recipes\CategoryController;
use App\Http\Controllers\Recipes\EvaluationController;
use App\Http\Controllers\Recipes\IngredientController;
//use App\Http\Controllers\Recipes\MediaController;
//use App\Http\Controllers\Recipes\QuantityController;
use App\Http\Controllers\Recipes\RecipeController;
use App\Http\Controllers\Users\UserController;
use Illuminate\Support\Facades\Route;

/**
 * Shopping List
 **/
Route::resource('shoppinglist', ShoppingListController::class);


/**
 * Homepage
 **/
Route::get('/', [RecipeController::class, 'manyrandom'])->name('welcome');

/**
 * Contact form
 **/
Route::get('/contact', function(){ return view('contact');})->name('contact.form');
Route::post('/contact', [ContactFormController::class, 'sendMail'])->name('contact.form');


/**
 * Recipes
 **/
Route::resource('recipes', RecipeController::class);
Route::resource('evaluation', EvaluationController::class);
Route::resource('ingredient', IngredientController::class);
//Route::resource('media', MediaController::class);
//Route::resource('quantity', QuantityController::class);

Route::get('/random', [RecipeController::class, 'random'])->name('random');

/**
 * Download Recipe as PDF
 **/
Route::get('/recipes/{recipe}/download', [RecipeController::class, 'download'])->name('recipes.download');

/**
 * Send Recipe
 **/
Route::get('/recipes/{recipe}/mail', [RecipeController::class, 'getmail'])->name('recipes.mail');
Route::post('/recipes/{recipe}/Send', [RecipeController::class, 'sendMail'])->name('recipes.send');

/**
 * Categories
 **/
Route::resource('categories', CategoryController::class);
Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{name}', [CategoryController::class, 'view']);

/**
 * Users
 **/
Route::resource('users', UserController::class);

/**
* BackOffice
**/
Route::middleware(['role:Administrator'])->group(function () {
    Route::get('/backoffice', [BackOfficeController::class, 'index'])->name('backoffice.index');
    Route::get('/backoffice/users', [BackOfficeController::class, 'users'])->name('backoffice.users');
    Route::get('/backoffice/roles', [BackOfficeController::class, 'roles'])->name('backoffice.roles');
    Route::get('/backoffice/recipes', [BackOfficeController::class, 'recipes'])->name('backoffice.recipes');

    Route::post('/backoffice/savepermission', [BackOfficeController::class, 'savePermission'])->name('backoffice.saveperm');
    Route::post('/backoffice/saverole', [BackOfficeController::class, 'saveRole'])->name('backoffice.saverole');
});


/**
 * DashBord
 **/
Route::get('/dashboard', [UserController::class, 'index'])->middleware(['auth'])->name('dashboard');

Route::get('users/{user}', [UserController::class, 'show'])->name('users.show')->middleware(['auth']);
Route::get('users/{user}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware(['auth']);

require __DIR__.'/auth.php';

laravel-breeze/app/Models/Recipes/Category.php
<?php

namespace App\Models\Recipes;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'type',
        'subtype1',
        'subtype2',
    ];

}

laravel-breeze/app/Models/Recipes/Evaluation.php
<?php

namespace App\Models\Recipes;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Evaluation extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'date',
        'comment',
        'recipe_id',
        'user_id',
        'rating',
    ];

    public function recipe()
    {
        return $this->hasOne(Recipe::class);
    }
}

laravel-breeze/app/Models/Recipes/Ingredient.php
<?php

namespace App\Models\Recipes;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Ingredient extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'name',
    ];

    public function quantities() : BelongsToMany
    {
            return $this->belongsToMany(Quantity::class);
    }

}

laravel-breeze/app/Models/Recipes/Media.php
<?php

namespace App\Models\Recipes;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'description',
        'alt',
        'path',
        'recipe_id',
    ];

}

laravel-breeze/app/Models/Recipes/Quantity.php
<?php

namespace App\Models\Recipes;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Quantity extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',

        'ingredient_id',
        'recipe_id',

        'quantity',
        'unit',
    ];

    public function ingredient(): BelongsTo
    {
        return $this->belongsTo(Ingredient::class);
    }

}

laravel-breeze/app/Models/Recipes/Recipe.php
<?php

namespace App\Models\Recipes;

use App\Models\Users\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Recipe extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'name',
        'guest_number',
        'category_id',
        'description',
        'steps',
        'cook_duration',
        'resting_duration',
        'preparation_duration',
        'price_range',
        'difficulty',
        'user_id',
        'publish_time',
    ];

    public function user(): HasOne
    {
        return $this->hasOne(User::class);
    }

    public function quantities() : BelongsTo
    {
        return $this->belongsTo(Quantity::class);
    }

    public function evaluations(): BelongsToMany
    {
        return $this->belongsToMany(User::class, "evaluations");
    }

    public function ingredients(): BelongsToMany
    {
        return $this->belongsToMany(Ingredient::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

}

laravel-breeze/app/Models/Recipes/Steps.php
<?php

namespace App\Models\Recipes;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Steps extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'step',
        'recipe_id',
        'created_at',
        'updated_at',
    ];
}

laravel-breeze/app/Http/Controllers/API/RecipeController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Recipes\Evaluation;
use App\Models\Recipes\Media;
use App\Models\Recipes\Quantity;
use App\Models\Recipes\Recipe;
use App\Models\Users\Like;
use App\Models\Users\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function index()
    {
        return Response::json(Recipe::all());
    }

    /**
     * Display the specified resource.
     *
     * @param Recipe $recipe
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function show(Recipe $recipe)
    {
        return Response::json($recipe);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Recipe $recipe
     * @return \Illuminate\Http\Response
     */
    public function destroy(Recipe $recipe)
    {
        Schema::disableForeignKeyConstraints();
        $recipe->delete();
        $quantities = Quantity::all()->where("recipe_id", "=", $recipe->id);
        foreach($quantities as $quantity)
        {
            $quantity->delete();
        }
        $medias = Media::all()->where("recipe_id", "=", $recipe->id);
        foreach($medias as $media)
        {
            $media->delete();
        }
        $evaluations = Evaluation::all()->where("recipe_id", "=", $recipe->id);
        foreach($evaluations as $evaluation)
        {
            $evaluation->delete();
        }
        $likes = Like::all()->where("recipe_id", "=", $recipe->id);
        foreach($likes as $like)
        {
            $like->delete();
        }
        Schema::enableForeignKeyConstraints();
        return back();
    }

    public function favorites()
    {
        $favRecipes = User::find(auth()->user()->id)->likes; // auth()->user()->id
        return Response::json($favRecipes);
    }

    public function myRecipes()
    {
        $myRecipes = Recipe::all()->where("user_id", "=", auth()->user()->id ); // auth()->user()->id
        return Response::json($myRecipes);
    }

    public function lastRecipes()
    {
        $recipes = DB::table("recipes")->orderByDesc("publish_time")->get();
        $lastRecipes = [];
        for($i = 0; $i<9; $i++)
        {
            $lastRecipes[] = $recipes[$i];
        }

        return Response::json($lastRecipes);
    }

    public function random()
    {
        $recipes = Recipe::all();
        $recipe = $recipes[rand(0, count($recipes)-1)];

        return Response::json($recipe);
    }

    public function search($subString)
    {
        $recipes = Recipe::query()->where('name', 'LIKE', "%{$subString}%")->get();
        return Response::json($recipes);
    }
}

laravel-breeze/app/Http/Controllers/Recipes/CategoryController.php
<?php

namespace App\Http\Controllers\Recipes;

use App\Http\Controllers\Controller;

use App\Models\Recipes\Category;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('categories', ['categories' => $categories]);

    }

    public function view(Request $request, $id)
    {
        $category = Category::where('id', $id)->first();
        return view('category', ['category' => $category]);
    }

}

laravel-breeze/app/Http/Controllers/Recipes/EvaluationController.php
<?php

namespace App\Http\Controllers\Recipes;

use App\Http\Controllers\Controller;

use App\Models\Recipes\Evaluation;
use Illuminate\Http\Request;

class EvaluationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function show(Evaluation $evaluation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function edit(Evaluation $evaluation)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Evaluation $evaluation)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Evaluation $evaluation)
    {
        //
    }
}

laravel-breeze/app/Http/Controllers/Recipes/IngredientController.php
<?php

namespace App\Http\Controllers\Recipes;

use App\Http\Controllers\Controller;
use App\Models\Recipes\Ingredient;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class IngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $recipes = DB::select('select * from recipes', [1]);

        return view('welcome', ['recipes' => $recipes]);
    }

}

laravel-breeze/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

laravel-breeze/resources/views/recipes/create.blade.php
<x-app-layout>
    <x-slot name="header">
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Creation d'une recette

                    <form action="{{ route('recipes.store') }}" method="post" enctype="multipart/form-data" class="flex flex-col gap-2">
                        @csrf

                        <x-label value="Nom de la recette" for="name" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                        <x-input id="name" name="name" type="text" class="w-full border-2 h-10"></x-input>

                        <x-label value="Description" for="description" ></x-label>
                        <textarea id="description" name="description" class="w-full border-2 h-40"></textarea>

                        <x-label value="Categorie" for="category_id" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                        <select name="category_id" id="category_id" class="w-full rounded-lg border-2">
                            <option value="">Séléctionner une catégorie</option>
                            @foreach(App\Models\Recipes\Category::all() as $category)
                                <option value="{{ $category->id }}">{{ $category->type }}</option>
                            @endforeach
                        </select>

                        <div class="details flex flex-row justify-between">
                            <div class="image w-1/2">
                                <div class="preview">
                                    <img id="file-ip-1-preview" class="w-full" src="" alt="">
                                </div>

                                <x-label value="Image" for="image" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <x-input onchange="displayImage(event)" id="image" name="image" type="file" class="border-2 rounded-lg"></x-input>
                                @error('image')
                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="infos_recipe w-2/5 flex flex-col gap-2">

                                <x-label value="Prix" for="price_range" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <select required name="price_range" class="w-full rounded-lg border-2">
                                    <option value="Eco +">Eco +</option>
                                    <option value="Moyen">Moyen</option>
                                    <option value="PIB Suisse">PIB Suisse</option>
                                </select>

                                <x-label value="Difficulté" for="difficulty" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <select required name="difficulty" class="w-full rounded-lg border-2">
                                    <option value="Facile">Facile</option>
                                    <option value="Moyen">Moyen</option>
                                    <option value="Difficile">Difficile</option>
                                </select>

                                <x-label value="Durée de préparation (min)" for="preparation_duration" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <x-input required id="preparation_duration" name="preparation_duration" type="number" class="w-full border-2 h-10"></x-input>

                                <x-label value="Durée de repos (min)" for="resting_duration" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <x-input required id="resting_duration" name="resting_duration" type="number" class="w-full border-2 h-10"></x-input>

                                <x-label value="Durée de cuisson (min)" for="cook_duration" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <x-input required id="cook_duration" name="cook_duration" type="number" class="w-full border-2 h-10"></x-input>


                            </div>

                        </div>



                        <x-label value="Nombre de personnes" for="guest_number" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                        <x-input id="guest_number" name="guest_number" type="number" class="w-full rounded-lg border-2"></x-input>


                        <div id="ingredients_list">


                            <div class="ingredient" id="copyNode">
                                <x-label value="ingredient" for="ingredients" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <select id="ingredients" onchange="get_value(this)" class="w-2/5 rounded-lg border-2">
                                    <option value="">Séléctionner un ingrédient</option>
                                    @foreach(App\Models\Recipes\Ingredient::all() as $ingredient)
                                        <option name="{{ $ingredient->id }}" value="{{ $ingredient->id }}">{{ $ingredient->name }}</option>
                                    @endforeach
                                </select>

                                <x-input id="ingredients_id_1" name="ingredients[{{ $ingredient->id }}][id]" value="{{ $ingredient->id }}" type="hidden" class="mt-1 form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5"></x-input>
                                <x-input id="ingredients_quantity_1" name="ingredients[{{ $ingredient->id }}][quantity]" placeholder="Quantité" type="number" class="w-1/3 rounded-lg border-2" required></x-input>
                                <select id="ingredients_unit_1" name="ingredients[{{ $ingredient->id }}][unit]" class="w-1/9 rounded-lg border-2" required>
                                    <option value="g">g</option>
                                    <option value="kg">kg</option>
                                    <option value="ml">ml</option>
                                    <option value="cL">cL</option>
                                    <option value="l">l</option>
                                </select>
                            </div>

                        </div>


                        <button onclick="add_ingredient()" type="button">Ajouter un ingrédient</button>


                        <div class="steps_list" id="steps_list">
                            <div id="step_copyNode">
                                <x-label value="Étapes" for="steps" class="block text-sm font-medium leading-5 text-gray-700"></x-label>
                                <textarea required id="steps" name="steps[1]" type="text" class="w-full rounded-lg border-2 h-20"></textarea>
                            </div>
                        </div>

                        <button onclick="add_step()" type="button">Ajouter une étape</button>

                        <button type="submit" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded">Créer la recette</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        var number_of_ingredients = 1;

        function get_value(object) {
            let value = object.value;

            let ingredients_id = object.nextElementSibling;
            ingredients_id.value = value;
            ingredients_id.name = "ingredients[" + value + "][id]";

            let ingredients_quantity = ingredients_id.nextElementSibling;
            ingredients_quantity.name = "ingredients[" + value + "][quantity]";

            let ingredients_unit = ingredients_quantity.nextElementSibling;
            ingredients_unit.name = "ingredients[" + value + "][unit]";


        }

        function add_ingredient(){

            number_of_ingredients++;

            let list = document.getElementById('ingredients_list');
            let copyNode = document.getElementById('copyNode');
            let newNode = copyNode.cloneNode(true);

            // newNode.id = 'copyNode' + number_of_ingredients;
            newNode.children[1].id = 'ingredients_id_' + number_of_ingredients;
            newNode.children[1].name = 'ingredients['+ number_of_ingredients +'][id]';
            newNode.children[2].id = 'ingredients_quantity_' + number_of_ingredients;
            newNode.children[2].name = 'ingredients['+ number_of_ingredients +'][quantity]';
            newNode.children[3].id = 'ingredients_unit_' + number_of_ingredients;
            newNode.children[3].name = 'ingredients['+ number_of_ingredients +'][unit]';

            let button = document.createElement('button');
            button.type = 'button';
            button.innerHTML = 'Supprimer';
            button.classList.add('bg-red-500', 'hover:bg-red-700', 'text-white', 'font-bold', 'py-2', 'px-4', 'rounded');
            button.onclick = function(){
                this.parentElement.remove();
            };
            newNode.appendChild(button);

            list.appendChild(newNode);

        }

        var number_of_steps = 1;

        function add_step(){
            number_of_steps ++;

            let steps_list = document.getElementById('steps_list');
            let step_card = document.getElementById('step_copyNode');

            let details = document.createElement('div');
            details.classList.add('step');

            let input = document.createElement('textarea');
            input.type = 'text';
            input.name = 'steps[' + number_of_steps + ']';
            input.classList.add('w-full', 'rounded-lg', 'border-2', 'h-20');
            input.required = true;
            details.appendChild(input);

            let button = document.createElement('button');
            button.type = 'button';
            button.classList.add('bg-red-500', 'hover:bg-red-700', 'text-white', 'font-bold', 'py-2', 'px-4', 'rounded');
            button.innerHTML = 'Supprimer';
            button.onclick = function(){
                this.parentElement.remove();
            };
            details.appendChild(button);

            document.getElementById('steps').parentElement.appendChild(details);
        }

        function displayImage(event){
            if(event.target.files.length > 0){
                var src = URL.createObjectURL(event.target.files[0]);
                var preview = document.getElementById("file-ip-1-preview");
                preview.src = src;
                preview.style.display = "block";
            }
        }
    </script>

</x-app-layout>

laravel-breeze/resources/views/recipes/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Toutes les recettes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="details">
                        <div class="container flex flex-wrap mx-auto">

                            @foreach ($recipes as $recipe)
                                <div class="w-full p-2 rounded lg:w-1/3 md:w-1/2" >
                                    <a href="{{ route('recipes.show', [$recipe]) }}">

                                        @if($recipe->image == null)
                                            <img class="w-full" src="https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" alt="">
                                        @else
                                            <img class="w-full" src="{{ $recipe->image }}" alt="">
                                        @endif
                                        <div class="font-semibold text-xl text-gray-800 leading-tight h-10">
                                            {{ $recipe->name }}
                                        </div>
                                        <div>
                                            <b>Temps de préparation :</b>
                                            {{ $recipe->preparation_duration }}
                                        </div>
                                        <div>
                                            <b>Temps de cuisson :</b>
                                            {{ $recipe->cook_duration }}
                                        </div>
                                        <div>
                                            <b>Coût :</b>
                                            {{ $recipe->price_range }}
                                        </div>
                                        <div>
                                            <b>Difficulté :</b>
                                            {{ $recipe->difficulty }}
                                        </div>
                                        <div>
                                            <b>Description : </b>
                                            {{ $recipe->description }}
                                        </div>
                                    </a>
                                </div>
                            @endforeach

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

laravel-breeze/resources/views/recipes/mail.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Envoyer cette recette') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="details">
                        <div class="container flex flex-wrap mx-auto">

                            @if (session('status'))
                                <div class="alert alert-success">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <div class="page">
                                <form action="{{route('recipes.send', $recipe)}}" method="POST">
                                    @csrf

                                        <!-- Email Address -->
                                        <div class="w-full">
                                            <x-label for="email" :value="__('Email du destinataire')" />

                                            <x-input id="email" class="block mt-1 w-full" type="email" name="email"
                                                     :value="old('email')" required autofocus />
                                        </div>
                                        <div class="flex justify-center w-full">
                                            <div class="mb-3 w-full">
                                                <label for="FormControlTextarea"
                                                       class="form-label inline-block mb-2 text-gray-700">Message que vous souhaitez envoyer</label>
                                                <textarea
                                                    class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                                    id="FormControlTextarea" rows="10" name="message"></textarea>
                                            </div>
                                        </div>

                                    <button class="bg-blue-400 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded inline-flex items-center" type="submit">
                                        <svg class="h-6 w-6 text-white"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <rect x="3" y="5" width="18" height="14" rx="2" />  <polyline points="3 7 12 13 21 7" /></svg>
                                        <span>Envoyer</span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

laravel-breeze/resources/views/recipes/pdf.blade.php
<h1>{{ $recipe->name }}</h1>

<h2>{{ $recipe->description }}</h2>


<p>Difficulté : {{ $recipe->difficulty }}</p>
@if($mediaRecipe != null)
    <img src="{{ public_path($mediaRecipe->path) }}" alt="" width="200">
@endif



<p>Durée{{ $recipe->cook_duration }} min</p>

@for($i = 0; $i < count($stepsRecipe)-1; $i++)
    <p>Etape {{ $i+1 }}:  {{ $stepsRecipe[$i]['step'] }}</p>
@endfor

<p>Fourchette de prix{{ $recipe->price_range }}</p>