laravel-breeze/routes/web.php
<?php

use App\Http\Controllers\Admin\BackOfficeController;
use App\Http\Controllers\ContactFormController;
use App\Http\Controllers\ShoppingListController;
use App\Http\Controllers\Recipes\CategoryController;
use App\Http\Controllers\Recipes\EvaluationController;
use App\Http\Controllers\Recipes\IngredientController;
//use App\Http\Controllers\Recipes\MediaController;
//use App\Http\Controllers\Recipes\QuantityController;
use App\Http\Controllers\Recipes\RecipeController;
use App\Http\Controllers\Users\UserController;
use Illuminate\Support\Facades\Route;

/**
 * Shopping List
 **/
Route::resource('shoppinglist', ShoppingListController::class);


/**
 * Homepage
 **/
Route::get('/', [RecipeController::class, 'manyrandom'])->name('welcome');

/**
 * Contact form
 **/
Route::get('/contact', function(){ return view('contact');})->name('contact.form');
Route::post('/contact', [ContactFormController::class, 'sendMail'])->name('contact.form');


/**
 * Recipes
 **/
Route::resource('recipes', RecipeController::class);
Route::resource('evaluation', EvaluationController::class);
Route::resource('ingredient', IngredientController::class);
//Route::resource('media', MediaController::class);
//Route::resource('quantity', QuantityController::class);

Route::get('/random', [RecipeController::class, 'random'])->name('random');

/**
 * Download Recipe as PDF
 **/
Route::get('/recipes/{recipe}/download', [RecipeController::class, 'download'])->name('recipes.download');

/**
 * Send Recipe
 **/
Route::get('/recipes/{recipe}/mail', [RecipeController::class, 'getmail'])->name('recipes.mail');
Route::post('/recipes/{recipe}/Send', [RecipeController::class, 'sendMail'])->name('recipes.send');

/**
 * Categories
 **/
Route::resource('categories', CategoryController::class);
Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{name}', [CategoryController::class, 'view']);

/**
 * Users
 **/
Route::resource('users', UserController::class);

/**
* BackOffice
**/
Route::middleware(['role:Administrator'])->group(function () {
    Route::get('/backoffice', [BackOfficeController::class, 'index'])->name('backoffice.index');
    Route::get('/backoffice/users', [BackOfficeController::class, 'users'])->name('backoffice.users');
    Route::get('/backoffice/roles', [BackOfficeController::class, 'roles'])->name('backoffice.roles');
    Route::get('/backoffice/recipes', [BackOfficeController::class, 'recipes'])->name('backoffice.recipes');

    Route::post('/backoffice/savepermission', [BackOfficeController::class, 'savePermission'])->name('backoffice.saveperm');
    Route::post('/backoffice/saverole', [BackOfficeController::class, 'saveRole'])->name('backoffice.saverole');
});


/**
 * DashBord
 **/
Route::get('/dashboard', [UserController::class, 'index'])->middleware(['auth'])->name('dashboard');

Route::get('users/{user}', [UserController::class, 'show'])->name('users.show')->middleware(['auth']);
Route::get('users/{user}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware(['auth']);

require __DIR__.'/auth.php';

laravel-breeze/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

laravel-breeze/resources/views/categories.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Catégories') }}
        </h2>
    </x-slot>
    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @foreach ($categories as $category)
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <a href="é">
                    <div class="p-6 bg-white border-b border-gray-200 capitalize">
                        ➡️ 
                        @if($category->subtype2 == null)
                            @if($category->subtype1 == null)
                                {{ $category->type }}
                            @else
                                {{ $category->subtype1 }}
                            @endif
                        @else
                            {{ $category->subtype2 }}
                        @endif
                    </div>
                </a>
            </div>
            @endforeach

        </div>
    </div>
</x-app-layout>

laravel-breeze/resources/views/contact.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Contact') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="page">
                        <form action="{{route('contact.form')}}" method="POST">
                            @csrf
                            <div class="container">

                            <!-- Email Address -->
                            <div>
                                <x-label for="email" :value="__('Email')" />

                                <x-input id="email" class="block mt-1 w-full" type="email" name="email"
                                    :value="old('email')" required autofocus />
                            </div>

                            <!-- Sujet -->
                            <div>
                                <x-label for="sujet" :value="__('Sujet')" />

                                <x-input id="sujet" class="block mt-1 w-full" type="text" name="sujet"
                                    :value="old('sujet')" required autofocus />
                            </div>

                            <div class="flex justify-center">
                                <div class="mb-3 w-full">
                                    <label for="exampleFormControlTextarea1"
                                        class="form-label inline-block mb-2 text-gray-700">Message</label>
                                    <textarea
                                        class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                        id="exampleFormControlTextarea1" rows="10" name="message"></textarea>
                                </div>
                            </div>
                            <div class="flex p-1">
                                <button role="submit" class="p-3 bg-blue-500 text-white hover:bg-blue-400"
                                    required>Envoyer</button>
                            </div>
                        </div>
                        </form>

                    </div>
                </div>
</x-app-layout>

laravel-breeze/resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">


                    <div class="flex flex-col">
                        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
                            <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
                                <script defer src="https://unpkg.com/alpinejs@3.10.2/dist/cdn.min.js"></script>
                                <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />


                                <script src="https://unpkg.com/boxicons@2.1.2/dist/boxicons.js"></script>
                                <!-- page -->
                                <main class="min-h-screen w-full bg-gray-100 text-gray-700" x-data="layout">
                                    <!-- header page -->
                                    <header
                                        class="flex w-full items-center justify-between border-b-2 border-gray-200 bg-white p-2">
                                        <!-- logo -->
                                        <div class="flex items-center space-x-2">
                                            <button type="button" class="text-3xl" @click="asideOpen = !asideOpen"><i
                                                    class="bx bx-menu"></i></button>
                                        </div>

                                    </header>

                                    <div class="flex">
                                        <!-- aside -->
                                        <aside
                                            class="flex w-72 flex-col space-y-2 border-r-2 border-gray-200 bg-white p-2"
                                            style="height: 90.5vh" x-show="asideOpen">
                                            <a href="route('recipes.create')"
                                                class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                                                <span class="text-2xl"><i class="bx bx-fork"></i></span>
                                                <span>Nouvelle Recette</span>
                                            </a>

                                            <a href="#"
                                                class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                                                <span class="text-2xl"><i class="bx bx-fork"></i></span>
                                                <span>Mes recettes</span>
                                            </a>

                                            <a href="#"
                                                class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                                                <span class="text-2xl"><i class="bx bx-fork"></i></span>
                                                <span>Mes favoris</span>
                                            </a>
                                            <a href="#"
                                                class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                                                <span class="text-2xl"><i class="bx bx-fork"></i></span>
                                                <span>Panier</span>
                                            </a>
                                            <a href="#"
                                                class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                                                <span class="text-2xl"><i class="bx bx-user"></i></span>
                                                <span>Compte</span>
                                            </a>
                                        </aside>

                                        <!-- main content page -->
                                        <div class="w-full p-4">
                                            <div class="mb-4">
                                                <label class="text-xl text-gray-600">Nom de la recette <span
                                                        class="text-red-500">*</span></label></br>
                                                <input type="text" class="border-2 border-gray-300 p-2 w-full"
                                                    name="title" id="title" value="">
                                            </div>

                                            <div class="mb-4">
                                                <label class="text-xl text-gray-600">Description</label></br>
                                                <input type="text" class="border-2 border-gray-300 p-2 w-full"
                                                    name="description" id="description">
                                            </div>
                                            <div class="mb-4">
                                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK2nG24AYDm6FOEC7jIfgubO96GbRso2Xshu1f8abSYQ&s"
                                                    alt="">
                                                <input type="file" name="image" placeholder="Image">
                                            </div>

                                            <div class="mb-4">
                                                <div class="mb-4">
                                                    Préparation

                                                    <div class="sub-information">
                                                        <input type="number" min="0" value="0">
                                                        h
                                                        <input type="number" min="0" max="59" value="0">
                                                    </div>
                                                </div>
                                                <div class="mb-4">
                                                    Cuisson

                                                    <div class="sub-information">
                                                        <input type="number" min="0" value="0">
                                                        h
                                                        <input type="number" min="0" max="59" value="0">
                                                    </div>
                                                </div>
                                                <div class="mb-4">
                                                    Repos

                                                    <div class="sub-information">
                                                        <input type="number" min="0" value="0">
                                                        h
                                                        <input type="number" min="0" max="59" value="0">
                                                    </div>
                                                </div>
                                                <div class="mb-4">
                                                    Difficulté

                                                    <div class="mb-4">
                                                        <i class="material-icons">&#xe561;</i>
                                                        <select name="difficulty">
                                                            <option value="1">Facile</option>
                                                            <option value="2">Moyen</option>
                                                            <option value="3">Difficile</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="mb-4">
                                                    <span>Cout</span>

                                                    <div class="sub-information">
                                                        <i class="material-icons">&#xea15;</i>
                                                        <select name="cost">
                                                            <option value="1">Eco+</option>
                                                            <option value="2">Moyen</option>
                                                            <option value="3">5 étoiles</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="mb-4">
                                                    <span>Nombre de personnes</span>

                                                    <div class="sub-information">
                                                        <i class="material-icons">&#xe7fd;</i>
                                                        <input type="number" min="1" max="69" value="2">
                                                    </div>
                                                </div>

                                                <div class="mb-8">
                                                    <label class="text-xl text-gray-600">Étapes <span
                                                            class="text-red-500">*</span></label></br>
                                                    <textarea name="content" class="border-2 border-gray-500">

                            </textarea>
                                                </div>

                                                <div class="flex p-1">
                                                    <select class="border-2 border-gray-300 border-r p-2" name="action">
                                                        <option>Publier</option>
                                                        <option>Enregistrer</option>
                                                    </select>
                                                    <button role="submit"
                                                        class="p-3 bg-blue-500 text-white hover:bg-blue-400"
                                                        required>Envoyer</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </main>

                                <script>
                                document.addEventListener("alpine:init", () => {
                                    Alpine.data("layout", () => ({
                                        profileOpen: false,
                                        asideOpen: true,
                                    }));
                                });
                                </script>
                            </div>
                        </div>
                    </div>



                </div>
            </div>
        </div>
    </div>
</x-app-layout>

laravel-breeze/resources/views/shopping.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Faire mes courses') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Asiatique
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Finger Food
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Burgers
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Cuisine française
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Apéritif
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Desserts
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Léger
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Épicé
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Boissons
                </div>
            </div>
        </div>
    </div>
</x-app-layout>