laravel-breeze/routes/web.php
<?php

use App\Http\Controllers\Admin\BackOfficeController;
use App\Http\Controllers\ContactFormController;
use App\Http\Controllers\ShoppingListController;
use App\Http\Controllers\Recipes\CategoryController;
use App\Http\Controllers\Recipes\EvaluationController;
use App\Http\Controllers\Recipes\IngredientController;
//use App\Http\Controllers\Recipes\MediaController;
//use App\Http\Controllers\Recipes\QuantityController;
use App\Http\Controllers\Recipes\RecipeController;
use App\Http\Controllers\Users\UserController;
use Illuminate\Support\Facades\Route;

/**
 * Shopping List
 **/
Route::resource('shoppinglist', ShoppingListController::class);


/**
 * Homepage
 **/
Route::get('/', [RecipeController::class, 'manyrandom'])->name('welcome');

/**
 * Contact form
 **/
Route::get('/contact', function(){ return view('contact');})->name('contact.form');
Route::post('/contact', [ContactFormController::class, 'sendMail'])->name('contact.form');


/**
 * Recipes
 **/
Route::resource('recipes', RecipeController::class);
Route::resource('evaluation', EvaluationController::class);
Route::resource('ingredient', IngredientController::class);
//Route::resource('media', MediaController::class);
//Route::resource('quantity', QuantityController::class);

Route::get('/random', [RecipeController::class, 'random'])->name('random');

/**
 * Download Recipe as PDF
 **/
Route::get('/recipes/{recipe}/download', [RecipeController::class, 'download'])->name('recipes.download');

/**
 * Send Recipe
 **/
Route::get('/recipes/{recipe}/mail', [RecipeController::class, 'getmail'])->name('recipes.mail');
Route::post('/recipes/{recipe}/Send', [RecipeController::class, 'sendMail'])->name('recipes.send');

/**
 * Categories
 **/
Route::resource('categories', CategoryController::class);
Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{name}', [CategoryController::class, 'view']);

/**
 * Users
 **/
Route::resource('users', UserController::class);

/**
* BackOffice
**/
Route::middleware(['role:Administrator'])->group(function () {
    Route::get('/backoffice', [BackOfficeController::class, 'index'])->name('backoffice.index');
    Route::get('/backoffice/users', [BackOfficeController::class, 'users'])->name('backoffice.users');
    Route::get('/backoffice/roles', [BackOfficeController::class, 'roles'])->name('backoffice.roles');
    Route::get('/backoffice/recipes', [BackOfficeController::class, 'recipes'])->name('backoffice.recipes');

    Route::post('/backoffice/savepermission', [BackOfficeController::class, 'savePermission'])->name('backoffice.saveperm');
    Route::post('/backoffice/saverole', [BackOfficeController::class, 'saveRole'])->name('backoffice.saverole');
});


/**
 * DashBord
 **/
Route::get('/dashboard', [UserController::class, 'index'])->middleware(['auth'])->name('dashboard');

Route::get('users/{user}', [UserController::class, 'show'])->name('users.show')->middleware(['auth']);
Route::get('users/{user}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware(['auth']);

require __DIR__.'/auth.php';

laravel-breeze/app/Models/Users/Like.php
<?php

namespace App\Models\Users;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Like extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'user_id',
        'recipe_id',
    ];
}

laravel-breeze/app/Models/Users/Permission.php
<?php

namespace App\Models\Users;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'review',
        'self_editing',
        'all',
    ];
}

laravel-breeze/app/Models/Users/Role.php
<?php

namespace App\Models\Users;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'title',
        'permissions_id',
    ];
}
 

laravel-breeze/app/Models/Users/User.php
<?php

namespace App\Models\Users;

use App\Models\Recipes\Recipe;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'id',
        'first_name',
        'last_name',
        'email',
        'password',
        'role_id',
        'registration_date',
        'api_token',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function likes()
    {
        return $this->belongsToMany(Recipe::class, table:"likes");
    }

    public function recipes(): HasMany
    {
        return $this->hasMany(Recipe::class);
    }
}

laravel-breeze/app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Users\User;
use Illuminate\Http\Request;
use App\Models\Users\Like;
use App\Models\Recipes\Recipe;
use App\Models\Recipes\Evaluation;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Response;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function index()
    {
        return Response::json(User::all());
    }


    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return Response::json($user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $firstName = $request->all()["first_name"];
        $lastName = $request->all()["last_name"];
        $email = $request->all()["email"];
        if($request->all()["oldPW"] != null)
        {
            $oldPW = $request->all()["oldPW"];
            if(!Hash::check($oldPW, $user->password))
            {
                return back()->with('status', 'Mot de passe incorrecte !');
            }
            if($request->all()["newPW"] == null || $request->all()["newPWConf"] == null)
            {
                return back()->with('status', 'Veuillez saisir un mot de passe valide !');
            }

            $newPW = $request->all()["newPW"];
            $newPWConf = $request->all()["newPWConf"];

            if($newPW != $newPWConf)
            {
                return back()->with('status', 'Les mots de passe doivent être identiques !');
            }

            $user->update(["first_name" => $firstName, "last_name" => $lastName, "email" => $email, 'password' => Hash::make($newPW)]);
        }
        else
        {
            $user->update(["first_name" => $firstName, "last_name" => $lastName, "email" => $email]);
        }

        return redirect()->route('dashboard', ["user" => Auth::user()])->with('status', 'Profil modifié !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        Schema::disableForeignKeyConstraints();
        $recipes = Recipe::all()->where('user_id', $user->id);
        foreach($recipes as $recipe)
        {
            $recipe->update(["user_id" => null]);
        }
        $likes = Like::all()->where("user_id", "=", $user->id);
        foreach($likes as $like)
        {
            $like->delete();
        }
        $evaluations = Evaluation::all()->where("user_id", "=", $user->id);
        foreach($evaluations as $evaluation)
        {
            $evaluation->update(["user_id" => null]);
        }
        $user->delete();
        Schema::enableForeignKeyConstraints();
        return back();
    }
}

laravel-breeze/app/Http/Controllers/Users/PermissionController.php
<?php

namespace App\Http\Controllers\Users;

use App\Models\Users\Permission;
use App\Http\Controllers\Controller;
use App\Http\Requests\StorePermissionRequest;
use App\Http\Requests\UpdatePermissionRequest;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categoryList = Category::all();
        return view('categories', compact('categoryList'));
    }

}

laravel-breeze/app/Http/Controllers/Users/UserController.php
<?php

namespace App\Http\Controllers\Users;

use App\Models\Users\Role;
use App\Models\Users\User;
use App\Models\Recipes\Recipe;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Controllers\Controller;
use App\Models\Recipes\Ingredient;
use App\Models\Recipes\Quantity;
use App\Models\ShoppingList;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{

    public function index()
    {
        $user = Auth::user();
        $role = Role::where("id", $user->role_id)->first();
        $myRecipes = $this->myRecipes();
        $favRecipes = User::find(auth()->user()->id)->likes;
        $shoppingList = ShoppingList::where("user_id", $user->id)->get();
        $recipes = Recipe::all();
        $quantities = Quantity::all();
        $ingredients = Ingredient::all();
        return view('users.dashboard', [
            "user" => $user,
            "role" => $role,
            "myRecipes" => $myRecipes,
            "favRecipes" => $favRecipes,
            "shoppingList" => $shoppingList,
            "recipes" => $recipes,
            "quantities" => $quantities,
            "ingredients" => $ingredients,
        ]);
    }

    public function show(User $user)
    {
        $role = Role::where("id", $user->role_id)->first();
        return view('users.show', ["user" => $user, "role" => $role]);
    }

    public function edit(User $user)
    {
        $role = Role::where("id", $user->role_id)->first();
        return view('users.edit', ["user" => $user, "role" => $role]);
    }

    private function myRecipes()
    {
        $myRecipes = Recipe::all()->where("user_id", "=", auth()->user()->id );
        return $myRecipes;
    }
}

laravel-breeze/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

laravel-breeze/resources/views/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Modification du profil') }}
        </h2>
    </x-slot>
    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="container">
                <div class="Info p-6 bg-white border-b border-gray-200 capitalize">
                    <form id="userForm" method="POST" action="{{ route('api.users.update', [$user,'api_token' => Auth::user()->api_token]) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <fieldset>
                            <legend><b>Prenom</b></legend>
                            <input type="text" name="first_name" value="{{ $user->first_name }}" class="border-transparent focus:border-transparent focus:ring-0">
                        </fieldset>
                        <fieldset>
                            <legend><b>Nom</b></legend>
                            <input type="text" name="last_name" value="{{ $user->last_name }}" class="border-transparent focus:border-transparent focus:ring-0">
                        </fieldset>
                        <fieldset>
                            <legend><b>Email</b></legend>
                            <input type="text" name="email" value="{{ $user->email }}" class="border-transparent focus:border-transparent focus:ring-0">
                        </fieldset>
                        <fieldset>
                            <legend><b>Ancien mot de passe</b></legend>
                            <input type="password" name="oldPW" value="" class="border-transparent focus:border-transparent focus:ring-0">
                        </fieldset>
                        <fieldset>
                            <legend><b>Nouveau mot de passe</b></legend>
                            <input type="password" name="newPW" value="" class="border-transparent focus:border-transparent focus:ring-0">
                        </fieldset>
                        <fieldset>
                            <legend><b>Confirmer mot de passe</b></legend>
                            <input type="password" name="newPWConf" value="" class="border-transparent focus:border-transparent focus:ring-0">
                        </fieldset>
                    </form>
                </div>
                <div class="Photo p-6 bg-white border-b border-gray-200 capitalize">
                    <img height="500" width="500" src="https://sbcf.fr/wp-content/uploads/2018/03/sbcf-default-avatar.png" class="simpleBorder">
                </div>
                <div class="p-6 bg-white border-b border-gray-200 capitalize buttonDiv">
                    <button type="submit" form="userForm" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full editButton">Valider</button>
                    <a href="{{ route('dashboard', [Auth::user()->id]) }}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full editButton">Annuler</a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

<style>
.container {
    display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr;
  gap: 0px 0px;
  grid-auto-flow: row;
  grid-template-areas:
    "Info Photo";
}

.Info {
    grid-area: Info;
    display: flex;
    flex-direction: column;
}
.Photo {
    grid-area: Photo;
}

fieldset{
    border: 1px solid black;
    padding-left: 2%;
    padding-bottom: 2%;
    width: 50%;
    margin-top: 5%;
    margin-left: 5%;
}
legend{
    padding: 0 1%;
}
.buttonDiv{
    width: 200%;
    display: flex;
    flex-direction: row;
    justify-content: center   ;
}

.simpleBorder{
    border: 1px solid black;
}

.editButton{
     margin: 0 5%;
}

input[type=text]:focus,input[type=password]:focus{
    border-bottom: 2px solid #ffa56d;
}
</style>

laravel-breeze/resources/views/users/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Profil') }}
        </h2>
    </x-slot>
    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="container">
                <div class="Info p-6 bg-white border-b border-gray-200 capitalize">
                    <fieldset>
                        <legend><b>Prenom</b></legend>
                        <label>{{ $user->first_name }}</label>
                    </fieldset>
                    <fieldset>
                        <legend><b>Nom</b></legend>
                        <label>{{ $user->last_name }}</label>
                    </fieldset>
                    <fieldset>
                        <legend><b>Email</b></legend>
                        <label>{{ $user->email }}</label>
                    </fieldset>
                    <fieldset>
                        <legend><b>Role</b></legend>
                        <label>{{ $role->title }}</label>
                    </fieldset>
                </div>
                <div class="Photo p-6 bg-white border-b border-gray-200 capitalize">
                    <img height="500" width="500" src="https://sbcf.fr/wp-content/uploads/2018/03/sbcf-default-avatar.png" class="simpleBorder">
                </div>
                <div class="p-6 bg-white border-b border-gray-200 capitalize buttonDiv">
                    <a href="{{ route('users.edit', $user) }}" class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-full">Modifier le profil</a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

<style>
.container {
    display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr;
  gap: 0px 0px;
  grid-auto-flow: row;
  grid-template-areas:
    "Info Photo";
}

.Info {
    grid-area: Info;
    display: flex;
    flex-direction: column;
}
.Photo {
    grid-area: Photo;
}

fieldset{
    border: 1px solid black;
    padding-left: 2%;
    padding-bottom: 2%;
    width: 50%;
    margin-top: 5%;
    margin-left: 5%;
}
legend{
    padding: 0 1%;
}
.buttonDiv{
    width: 200%;
    display: flex;
    flex-direction: row;
    justify-content: space-evenly;
}

.simpleBorder{
    border: 1px solid black;
}
</style>