laravel-breeze/routes/web.php
<?php

use App\Http\Controllers\Admin\BackOfficeController;
use App\Http\Controllers\ContactFormController;
use App\Http\Controllers\ShoppingListController;
use App\Http\Controllers\Recipes\CategoryController;
use App\Http\Controllers\Recipes\EvaluationController;
use App\Http\Controllers\Recipes\IngredientController;
//use App\Http\Controllers\Recipes\MediaController;
//use App\Http\Controllers\Recipes\QuantityController;
use App\Http\Controllers\Recipes\RecipeController;
use App\Http\Controllers\Users\UserController;
use Illuminate\Support\Facades\Route;

/**
 * Shopping List
 **/
Route::resource('shoppinglist', ShoppingListController::class);


/**
 * Homepage
 **/
Route::get('/', [RecipeController::class, 'manyrandom'])->name('welcome');

/**
 * Contact form
 **/
Route::get('/contact', function(){ return view('contact');})->name('contact.form');
Route::post('/contact', [ContactFormController::class, 'sendMail'])->name('contact.form');


/**
 * Recipes
 **/
Route::resource('recipes', RecipeController::class);
Route::resource('evaluation', EvaluationController::class);
Route::resource('ingredient', IngredientController::class);
//Route::resource('media', MediaController::class);
//Route::resource('quantity', QuantityController::class);

Route::get('/random', [RecipeController::class, 'random'])->name('random');

/**
 * Download Recipe as PDF
 **/
Route::get('/recipes/{recipe}/download', [RecipeController::class, 'download'])->name('recipes.download');

/**
 * Send Recipe
 **/
Route::get('/recipes/{recipe}/mail', [RecipeController::class, 'getmail'])->name('recipes.mail');
Route::post('/recipes/{recipe}/Send', [RecipeController::class, 'sendMail'])->name('recipes.send');

/**
 * Categories
 **/
Route::resource('categories', CategoryController::class);
Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{name}', [CategoryController::class, 'view']);

/**
 * Users
 **/
Route::resource('users', UserController::class);

/**
* BackOffice
**/
Route::middleware(['role:Administrator'])->group(function () {
    Route::get('/backoffice', [BackOfficeController::class, 'index'])->name('backoffice.index');
    Route::get('/backoffice/users', [BackOfficeController::class, 'users'])->name('backoffice.users');
    Route::get('/backoffice/roles', [BackOfficeController::class, 'roles'])->name('backoffice.roles');
    Route::get('/backoffice/recipes', [BackOfficeController::class, 'recipes'])->name('backoffice.recipes');

    Route::post('/backoffice/savepermission', [BackOfficeController::class, 'savePermission'])->name('backoffice.saveperm');
    Route::post('/backoffice/saverole', [BackOfficeController::class, 'saveRole'])->name('backoffice.saverole');
});


/**
 * DashBord
 **/
Route::get('/dashboard', [UserController::class, 'index'])->middleware(['auth'])->name('dashboard');

Route::get('users/{user}', [UserController::class, 'show'])->name('users.show')->middleware(['auth']);
Route::get('users/{user}/edit', [UserController::class, 'edit'])->name('users.edit')->middleware(['auth']);

require __DIR__.'/auth.php';

laravel-breeze/app/Http/Controllers/Admin/BackOfficeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Users\Permission;
use App\Models\Users\Role;
use App\Models\Users\User;
use App\Models\Recipes\Recipe;
use App\Models\Recipes\Category;
use App\Models\Recipes\Quantity;
use Illuminate\Http\Request;

class BackOfficeController extends Controller
{
    public function index()
    {
        return view('backoffice.back');
    }

    public function users()
    {
        $users = User::all();
        $roles = Role::all();
        return view('backoffice.users', ["users" => $users, "roles" => $roles]);
    }

    public function roles()
    {
        $roles = Role::all();
        $permissions = Permission::all();
        return view('backoffice.roles', ["permissions" => $permissions, "roles" => $roles]);
    }

    public function savePermission(Request $request)
    {
        $perms = $request->all();
        unset($perms["_token"]);
        $permsKeys = array_keys($perms);
        $perm = array_shift($permsKeys);
        if($perm != "permID")
        {
            $permID = explode("permission", $perm)[1];
            $permission = Permission::where("id", $permID)->first();

            $perms = array_shift($perms);
            $review = in_array("review", $perms);
            $selfEdit = in_array("selfEdit", $perms);
            $all = in_array("all", $perms);
        }
        else
        {
            $permission = Permission::where("id", $perms["permID"])->first();

            $review = false;
            $selfEdit = false;
            $all = false;
        }

        $permission->update(["review" => $review, "self_editing" => $selfEdit, "all" => $all]);
        return redirect()->route('backoffice.roles');

    }

    public function saveRole(Request $request)
    {
        $role = $request->all();
        $roleID = $role["role"];
        $userID = $role["userID"];

        $user = User::where("id", $userID)->first();
        $user->update(["role_id" => $roleID]);
        return redirect()->route('backoffice.users');

    }

    public function recipes()
    {
        $recipes = Recipe::all();
        $categories = Category::all();
        $quantities = Quantity::all();
        return view('backoffice.recipes', ["recipes" => $recipes, "categories" => $categories, "quantities"=> $quantities]);
    }
}

laravel-breeze/app/Http/Controllers/BackOfficeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Users\Permission;
use App\Models\Users\Role;
use App\Models\Users\User;
use App\Models\Recipes\Recipe;
use App\Models\Recipes\Category;
use App\Models\Recipes\Quantity;
use Illuminate\Http\Request;

class BackOfficeController extends Controller
{
    public function index()
    {
        return view('backoffice.back');
    }

    public function users()
    {
        $users = User::all();
        $roles = Role::all();
        return view('backoffice.users', ["users" => $users, "roles" => $roles]);
    }

    public function roles()
    {
        $roles = Role::all();
        $permissions = Permission::all();
        return view('backoffice.roles', ["permissions" => $permissions, "roles" => $roles]);
    }

    public function savePermission(Request $request)
    {
        $perms = $request->all();
        unset($perms["_token"]);
        $permsKeys = array_keys($perms);
        $perm = array_shift($permsKeys);
        if($perm != "permID")
        {
            $permID = explode("permission", $perm)[1];
            $permission = Permission::where("id", $permID)->first();
    
            $perms = array_shift($perms);
            $review = in_array("review", $perms);
            $selfEdit = in_array("selfEdit", $perms);
            $all = in_array("all", $perms);
        }
        else
        {
            $permission = Permission::where("id", $perms["permID"])->first();
            
            $review = false;
            $selfEdit = false;
            $all = false;
        }
        
        $permission->update(["review" => $review, "self_editing" => $selfEdit, "all" => $all]);
        return redirect()->route('backoffice.roles');

    }

    public function saveRole(Request $request)
    {
        $role = $request->all();
        $roleID = $role["role"];
        $userID = $role["userID"];

        $user = User::where("id", $userID)->first();
        $user->update(["role_id" => $roleID]);
        return redirect()->route('backoffice.users');

    }

    public function recipes()
    {
        $recipes = Recipe::all();
        $categories = Category::all();
        $quantities = Quantity::all();
        return view('backoffice.recipes', ["recipes" => $recipes, "categories" => $categories, "quantities"=> $quantities]);
    }
}

laravel-breeze/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

laravel-breeze/resources/views/backoffice/back.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('BackOffice') }}
        </h2>
    </x-slot>
    <div class="py-12">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <a href="{{ route('backoffice.users') }}">
                <div class="p-6 bg-white border-b border-gray-200 capitalize">
                    ➡️ Utilisateurs
                </div>
            </a>
            <a href="{{ route('backoffice.roles') }}">
                <div class="p-6 bg-white border-b border-gray-200 capitalize">
                    ➡️ Roles
                </div>
            </a>
            <a href="{{ route('backoffice.recipes') }}">
                <div class="p-6 bg-white border-b border-gray-200 capitalize">
                    ➡️ Recettes
                </div>
            </a>
        </div>
    </div>
</x-app-layout>

laravel-breeze/resources/views/backoffice/recipes.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <a href="{{ route('backoffice.index') }}">⬅</a> {{ __('Recettes') }}
        </h2>
    </x-slot>
    <div class="py-12" style="background-color: #22577A;">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <table>
                    <tr style="font-size: 150%;" class="border-b border-gray-200">
                        <td>
                            <div class="p-6 bg-white capitalize">
                                ID
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Titre
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Categorie
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Ingredients
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Participants
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Gestion
                            </div>
                        </td>
                    </tr>
                    @foreach ($recipes as $recipe)
                        <tr class="border-b border-gray-200">
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $recipe->id }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $recipe->name }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        @foreach($categories as $category)
                                            @if($category->id == $recipe->category_id)
                                                @if($category->subtype2 == null)
                                                    @if($category->subtype1 == null)
                                                        {{ $category->type }}
                                                    @else
                                                        {{ $category->subtype1 }}
                                                    @endif
                                                @else
                                                    {{ $category->subtype2 }}
                                                @endif
                                            @endif
                                        @endforeach
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ count($quantities->where("recipe_id", $recipe->id)) }} Ingredients
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $recipe->guest_number }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        <a href="{{route('recipes.edit', $recipe->id)}}">
                                            ✒ Editer
                                        </a>
                                        <form action="{{ route('api.recipes.destroy', [$recipe->id, 'api_token' => Auth::user()->api_token]) }}" method="POST">
                                            @method('delete')
                                            @csrf
                                            <button type="submit">
                                                ❌ Supprimer
                                            </button>
                                        </form>
                                    </div>
                                </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
</x-app-layout>

<style>
    table{
        text-align: center ;
        width:100%;
    }
</style>

laravel-breeze/resources/views/backoffice/roles.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <a href="{{ route('backoffice.index') }}">⬅</a> {{ __('Roles') }}
        </h2>
    </x-slot>
    <div class="py-12" style="background-color: #22577A;">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <table>
                    <tr style="font-size: 150%;" class="border-b border-gray-200">
                        <td>
                            <div class="p-6 bg-white capitalize">
                                ID
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Titre
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Permissions
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Gestion
                            </div>
                        </td>
                    </tr>
                    @foreach ($roles as $role)
                        <tr class="border-b border-gray-200">
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $role->id }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $role->title }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        <form id="{{'permForm'.$role->id}}" method="POST" action="{{ route('backoffice.saveperm') }}" enctype="multipart/form-data">
                                            @csrf
                                            @foreach($permissions as $permission)
                                                @if($role->permissions_id == $permission->id)
                                                <ul class="permList">
                                                        <li>
                                                            <div class="permDiv">
                                                                <b>Review</b>
                                                                @if($role->title == "Administrator")
                                                                    {{ Form::checkbox('permission'.$permission->id.'[]', 'review', $permission->review, array('disabled') )}}
                                                                @else
                                                                    {{ Form::checkbox('permission'.$permission->id.'[]', 'review', $permission->review)}}
                                                                @endif
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="permDiv">
                                                                <b>SelfEdit</b>
                                                                @if($role->title == "Administrator")
                                                                {{ Form::checkbox('permission'.$permission->id.'[]', 'selfEdit', $permission->self_editing, array('disabled') )}}
                                                                @else
                                                                {{ Form::checkbox('permission'.$permission->id.'[]', 'selfEdit', $permission->self_editing) }}
                                                                @endif
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="permDiv">
                                                                <b>All</b>
                                                                @if($role->title == "Administrator")
                                                                {{ Form::checkbox('permission'.$permission->id.'[]', 'all', $permission->all, array('disabled') )}}
                                                                @else
                                                                {{ Form::checkbox('permission'.$permission->id.'[]', 'all', $permission->all) }}
                                                                @endif
                                                            </div>
                                                        </li>
                                                </ul>
                                                <input type="hidden" value="{{ $permission->id }}" name="permID"/>     
                                                @endif
                                            @endforeach
                                        </form>
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                            <button type="submit" form="{{'permForm'.$role->id}}">
                                                ✔ Valider
                                            </button>
                                            <form action="{{ route('api.roles.destroy', [$role->id, 'api_token' => Auth::user()->api_token]) }}" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button type="submit">
                                                    ❌ Supprimer
                                                </button>
                                            </form>
                                        
                                    </div>
                                </td>
                        </tr>
                    @endforeach
                    <tr class="border-b border-gray-200">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <div class="p-6 bg-white capitalize">                                
                                <a class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full" href="{{ route('backoffice.roles') }}">
                                    Cancel
                                </a>                                      
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>

<style>
    .permDiv{
       display: flex;
       justify-content: space-between; 
       width: 30%;
       margin-left: 35%;
    }

    .permList{
        margin: -20px 0 -15px 0;
    }

    input[type="checkbox"]:disabled {
        color: #ccc;
    }

    table{
        text-align: center ;
        width:100%;
    }

</style>

laravel-breeze/resources/views/backoffice/users.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <a href="{{ route('backoffice.index') }}">⬅</a> {{ __('Utilisateurs') }}
        </h2>
    </x-slot>
    <div class="py-12" style="background-color: #22577A;">

        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <table style="text-align: center ;width:100%">
                    <tr style="font-size: 150%;" class="border-b border-gray-200">
                        <td>
                            <div class="p-6 bg-white capitalize">
                                ID
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Prenom
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Nom
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Mail
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Role
                            </div>
                        </td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                Gestion
                            </div>
                        </td>
                    </tr>
                    @foreach ($users as $user)
                        <tr class="border-b border-gray-200">
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $user->id }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $user->first_name }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $user->last_name }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        {{ $user->email }}
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        <form id="{{'roleForm'.$user->id}}" method="POST" action="{{ route('backoffice.saverole') }}" enctype="multipart/form-data">
                                            @csrf
                                            <select name="role" class="block p-2 mb-6 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" {{$roles->where("id", $user->role_id)->first()->title == "Administrator" ? "disabled" : ""}}>
                                                @foreach($roles as $role)
                                                    <option value="{{ $role->id }}" {{ $role->id == $user->role_id ? 'selected="selected"' : '' }}>{{ $role->title }}</option>
                                                @endforeach
                                            </select>
                                            <input type="hidden" value="{{ $user->id }}" name="userID"/>
                                        </form>
                                    </div>
                                </td>
                                <td>
                                    <div class="p-6 bg-white capitalize">
                                        @if($roles->where("title", "Administrator")->first()->id != $user->role_id)
                                            <button type="submit" form="{{'roleForm'.$user->id}}">
                                                ✔ Valider
                                            </button>
                                            <form action="{{ route('api.users.destroy', [$user->id, 'api_token' => Auth::user()->api_token]) }}" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button type="submit">
                                                    ❌ Supprimer
                                                </button>
                                            </form>
                                        @endif
                                    </div>
                                </td>
                        </tr>
                    @endforeach
                    <tr class="border-b border-gray-200">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <div class="p-6 bg-white capitalize">
                                <a class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full" href="{{ route('backoffice.users') }}">
                                    Cancel
                                </a>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>

<style>
    table{
        text-align: center ;
        width:100%;
    }

    select{
        margin: -10px;
    }
</style>